### ISSUE TITLE
Non-intuitive behavior

### ISSUE THREAD

**Issue by Beckfield** [tranxuanthang/lrcget#100]
I was surprised by the following behavior:

My music library is configured as follows:
![image](https://github.com/tranxuanthang/lrcget/assets/4588823/7f3fafb8-fd9a-44ec-994d-42e6173016da)

1. Set scanning directory to parent of all music files ("Music"). LRCGet catalogs all files in all subfolders (roughly 4000 files).
2. Select the "Albums" tab.
3. Select any album.  LRCGet displays the contents of that album.
![image](https://github.com/tranxuanthang/lrcget/assets/4588823/f312105f-5f8f-4690-a55b-0cf3e863b253)

Everything is intuitive so far.  However, I was surprised when I clicked "Download All Lyrics" at this point.  I intuitively expected it to download just the lyrics for the tracks displayed, which are from the selected album.  But the actual behavior was that it started downloading lyrics for all 4000 files in the entire "Music" library.

I think it would be more intuitive if the "Download All Lyrics" button only downloaded lyrics for the currently-displayed list of tracks, OR if there were another button to only download lyrics for the album.

**Comment by ginjaninja1** [comment]
if you look at the list of artists, albums or tracks there is a icon against each artist, album or track  to download lyrics  for that [parent] object....

Once in an Album or Artist, i agree its counter intuitive the "download all lyrics" button is not slaved to your position in the library. or to put it another way it would be nice to have a button to down all lyrics for the objects in current focus.

**Comment by Beckfield** [comment]
_"if you look at the list of artists, albums or tracks there is a icon against each artist, album or track to download lyrics for that [parent] object...."_

I somehow failed to notice this, so that does alleviate part of the problem.  A tooltip when I hover over those icons would be nice.

**Comment by tranxuanthang** [comment]
Not the best solution, but in the upcoming version, there will be a button in album/artist tracks list for downloading lyrics for all tracks of that album/artist:

![image](https://github.com/user-attachments/assets/eae48da8-5830-45dd-84f8-e128b5c5093e)

**Comment by Beckfield** [comment]
Thanks!

**Comment by tranxuanthang** [comment]
Resolved in v0.5.0 🎉
