### ISSUE TITLE
Opus .oggs not appearing.

### ISSUE THREAD

**Issue by Droidiar** [tranxuanthang/lrcget#102]
I tried Opus in .ogg's so I could make lyrics for them because of #5  (Very outdated issue I recognize now) and I have observed that Opus in .ogg's just don't appear at all, despite their .opus counterparts appearing. Vorbis .ogg's appear though, weird!

**Comment by tranxuanthang** [comment]
I've reopened #5 so we can keep all Opus issues in one place. I'll close this issue to tidy up. Thanks!
