### ISSUE TITLE
Show songs in albums in correct order

### ISSUE THREAD

**Issue by fineless71** [tranxuanthang/lrcget#112]
Right now, when opening an album it shows the songs in alphabetical order instead of the track order.

**Comment by tueksta** [comment]
that'd be awesome, big step toward becoming a full time player.

**Comment by tranxuanthang** [comment]
I think we can ultilize the "Track Number" metadata. You can get it with `lofty` by [this key](https://docs.rs/lofty/latest/lofty/tag/enum.ItemKey.html#variant.TrackNumber). The metadata also needs to be added and indexed in the database so we can sort it in album view.

I'll try to implement that when I have some time, but PR for this is welcome.

**Comment by tranxuanthang** [comment]
Support for album artist and track number has been added in this commit: https://github.com/tranxuanthang/lrcget/commit/71fa8c0aa84d8a71eeb823a8b06226eee06fb426. This means compilation albums with various artists are now grouped together nicely and displayed in the correct order, too!
