### ISSUE TITLE
Blank window on ubuntu 24.04

### ISSUE THREAD

**Issue by papampi** [tranxuanthang/lrcget#119]
When trying to run on ubuntu 24.04 gives this  with blank window
Tried both deb install and appimage

```
src/nv_gbm.c:300: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)


** (lrcget:133958): WARNING **: 13:10:49.938: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Database file path: /root/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 4
src/nv_gbm.c:300: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1024x768: Permission denied
```

Edit:
Runnig with `WEBKIT_DISABLE_DMABUF_RENDERER=1 lrcget ` solves the issue, but still shows this error:
`src/nv_gbm.c:300: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)
`

**Comment by tranxuanthang** [comment]
I'm sorry for late reply. If you are using an Nvidia GPU, then this may be related:

https://github.com/tranxuanthang/lrcget/issues/54#issuecomment-2094306594
