### ISSUE TITLE
Downloaded count went over total left

### ISSUE THREAD

**Issue by fineless71** [tranxuanthang/lrcget#131]
~I can't reproduce this but I'd figure I'd file a bug report:~ This happened to me again, but with a different song. Same symptoms, one of the duplicates is the very last one. Seems to happen ~50% of the time, maybe related to reloading but I'm not decently sure of the cause.

I pressed the "Download All Lyrics" button and it went past the max. (17/16)

![image](https://github.com/user-attachments/assets/b5ff3460-d082-49b2-90ac-6869122bec05)

Sorry for the censor: In the list, one of the songs is listed twice, one of them is at the end, and one is near the middle.

**Comment by fineless71** [comment]
![image](https://github.com/user-attachments/assets/e160321d-1b66-43fe-a98b-22a08cb1dec5)
I used the "Download Album Lyrics" and I got this happen, the bottom song is not in the album. This was shortly after I cancelling a download for all songs. Sorry for the censor before as it included songs I didn't want to share.

**Comment by fineless71** [comment]
This is 100% an assumption and I have no idea how the code works, but my guess is that when stopping a mass download, it doesn't cancel the active web requests, so when you start a new download and then a request from the previous download finishes, it gets added to the current one

**Comment by tranxuanthang** [comment]
I think I kind of fixed it in some recent commits, so allow me to close this issue for now in order to clean up!
