### ISSUE TITLE
bug: Publishing or updating lyrics seems to stop working after 3 publishes

### ISSUE THREAD

**Issue by DataM0del** [tranxuanthang/lrcget#141]
Any idea why?
After uploading synced lyrics for:
- "red is not your enemy"
- "mentor"
- "dempster"

(all of them are by twikipedia), trying to upload synced lyrics for "alone" or "GPS" by twikipedia (GPS was removed because the album it was in, named "die", was removed/deleted from all of twikipedia's platforms, but it's still on lrclib and some other platforms, like YouTube or Soundcloud)
The client says it uploaded the lyrics, but then when I search for it, it only shows "Plain", not synced, as it did for the 3 initial ones.

**Comment by tranxuanthang** [comment]
The `/search` API result is cached for about 24 hours, so it might take a while for you to see it. But the `/get` API is uncached so you can see your updated lyrics immediately.

**Comment by DataM0del** [comment]
Oh, well today it seems like it was uploaded. Make it more clear about the cache and how it will take 24 hours for it to be on LRCLIB because of the cache.

**Comment by DataM0del** [comment]
> > Oh, well today it seems like it was uploaded. Make it more clear about the cache and how it will take 24 hours for it to be on LRCLIB because of the cache.
> 
> ![image](https://private-user-images.githubusercontent.com/183248792/373947599-76b138af-bceb-4545-ba95-a35678f66bb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTkzMDMsIm5iZiI6MTcyODIxOTAwMywicGF0aCI6Ii8xODMyNDg3OTIvMzczOTQ3NTk5LTc2YjEzOGFmLWJjZWItNDU0NS1iYTk1LWEzNTY3OGY2NmJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMjUwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGY0NDlmZjdkZGQ3OWJmY2U4ZjlkMzA0NzIxM2YyMDdiNTM5MWFkMDg1NjRmMTM4NjZkY2ZhMmQ2ZDViNGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._rTDdQrE0FlDRGrdpI1BkIDk0Vk81pw7xWVpy6UnvU4)

Yep, it does (also usually I don't include the metadata for the songs but I included it now, even though I probably shouldn't because 99% of the lyrics don't have the metadata so programs implementing their own parsing of these may not work properly, will remove it in a second).
![image](https://github.com/user-attachments/assets/f68846de-82f3-4652-a6a2-7c14ee39caa9)

**Comment by DataM0del** [comment]
Extra details: if you literally match the song name and the artist (e.g. "nameless - twikipedia"), it seems like there is no cache, however, if you search up just the artist / author, it has cache.
