### ISSUE TITLE
Publishing Lyrics Times Out on Requesting Challenge

### ISSUE THREAD

**Issue by riley-martine** [tranxuanthang/lrcget#159]
When attempting to publish lyrics, I get an error: `error sending request for url (https://lrclib.net/api/request-challenge)`

I changed the [timeout](https://github.com/tranxuanthang/lrcget/blob/39b921bb5ea6a106414b178c579ffe5540cf07ee/src-tauri/src/lrclib/request_challenge.rs#L28) to `100`, recompiled, and am able to successfully publish lyrics.

You can verify how long this takes with `curl`:

```console
$ time curl -X POST https://lrclib.net/api/request-challenge
{"prefix":"Hol7vo1iCVcpbHHjMmKEpDRzvLxzp4zo","target":"000000FF00000000000000000000000000000000000000000000000000000000"}
________________________________________________________
Executed in   18.34 secs      fish           external
   usr time   16.47 millis    0.13 millis   16.34 millis
   sys time   22.86 millis    1.62 millis   21.24 millis
```

I'm located in the US, not behind a VPN, have reasonably fast internet, and so I think the problem is not with me.

**Comment by tranxuanthang** [comment]
Yeah the `/request-challenge` API is currently quite slow at server-side, but this can certainly be further improved. I'll look into it as soon as I can.

**Comment by tranxuanthang** [comment]
It should be faster now, thank you for reporting this!

![image](https://github.com/user-attachments/assets/a75fdf2e-c327-4507-95ff-57f6f5610a77)

**Comment by riley-martine** [comment]
Oh that's much faster, thank you so much!

**Comment by amokprime** [comment]
I've been getting the same error intermittently this week and today I can't publish lyrics at all. It doesn't hang up but rather fails almost immediately in a few seconds. I tried a few different VPN servers in US and CA but it made no difference.
