### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by Vishnu5588** [tranxuanthang/lrcget#16]
I have both latest version of windows & the app. When I open LRCGET.exe It doesnt work, I tried running it as admin still nothing. The app isnt working. Someone please help..

**Comment by tranxuanthang** [comment]
Which version of Windows 10 are you using? (Home/Pro/LTSC/...)
Have you ever run any script to debloat Windows 10 or remove Microsoft Edge?

**Comment by Vishnu5588** [comment]
> 

Yah, I did removed Microsoft Edge.. I'm using Windows 10 pro.

**Comment by Vishnu5588** [comment]
> Which version of Windows 10 are you using? (Home/Pro/LTSC/...) Have you ever run any script to debloat Windows 10 or remove Microsoft Edge?

I'm using Windows 10 pro.
Yah, I did removed Microsoft Edge.. I use chrome as my default browser.

**Comment by tranxuanthang** [comment]
Could you try to install [WebView2 Bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) and see if LRCGET can open now?

Also I would not suggest removing Edge, because it breaks things and you may unable to successfully run Windows Update later.
