### ISSUE TITLE
Does Not See MP3 files  Flac ok

### ISSUE THREAD

**Issue by OldmanTym** [tranxuanthang/lrcget#17]
I saw this problem mentioned on a reddit  post from 10 months ago but no other mention of it. Love the program great tool but need some mp3 help. Using this on windows 11.

**Comment by OldmanTym** [comment]
ok figured what was wrong. Extension had to be in lower case .mp3  not .MP3   Not sure why they were saved that way.

**Comment by tranxuanthang** [comment]
I see. Uppercase MP3 should still be a valid mp3 extension though. I will address this in the next update.

**Comment by OldmanTym** [comment]
update its both flac and mp3 that need to be lowercase

**Comment by tranxuanthang** [comment]
This is fixed in v0.2.1:

https://github.com/tranxuanthang/lrcget/releases
