### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by korewaChino** [tranxuanthang/lrcget#18]
Hi! We would like to use your lrclib API to integrate into a music player. Could we have a proper API documentation for it?

I'm sorry if I'm in the wrong place, but since there's nowhere else to write I'll be writing it here instead.

**Comment by koehntopp** [comment]
I can offer the crappy Python code I hacked together:

`def get_lrclyrics (flactags):
   duration = f"{int(flactags.info.length // 60):d}{int(flactags.info.length % 60):02d}"
   url_template = "https://lrclib.net/api/get?{}"
   try:
      albumtitle = flactags['ORIGINAL_TITLE'][0]
   except KeyError:
      albumtitle = flactags['ALBUM'][0]
   params = {"track_name": flactags['TITLE'][0], "artist_name": flactags['ALBUMARTIST'][0], "album_name": albumtitle, "duration": duration}
   url = url_template.format(urlencode(params, safe="()", quote_via=quote))
   lyricsdata = ''
   try:
      response = requests.get(url)
      data = response.json()
      lyricsdata = (data['syncedLyrics'])
      if lyricsdata is None:
         lyricsdata = ''
   except:
      lyricsdata = ''
   return lyricsdata
`

**Comment by tranxuanthang** [comment]
The good news is I'm still working on a home and documentation page for lrclib.net. My time is limited though so it might take a while for me to finish.

**Comment by koehntopp** [comment]
This no longer works - I saw you have changed the order of parameters, is there anything else that's different...?

**Comment by tranxuanthang** [comment]
@koehntopp I did add some parameters to the *response* JSON of `get` API, but I don't remember changing or removing any, to keep it backward compatible.

**Comment by koehntopp** [comment]
Hmmm... maybe a more direct question - any idea why the following query returns a 404 - the App has LRC lyrics for that song:

https://lrclib.net/api/get?artist_name=Huey%20Lewis%20%26%20The%20News&track_name=If%20This%20Is%20It&album_name=Sports&duration=354

**Comment by tranxuanthang** [comment]
@koehntopp I see... I actually fixed some "bugs" that make LRCLIB find a match for a song that are not really closely equal in duration (+- 2s).

This is probably the record that was matched before: [https://lrclib.net/api/get/2148759](https://lrclib.net/api/get/2148759). The duration of it is way shorter (234s) than your track (354s).

If you don't need the pessimistic exact match, you may use the `search` API:

https://lrclib.net/api/search?artist_name=Huey%20Lewis%20%26%20The%20News&track_name=If%20This%20Is%20It&album_name=Sports

**Comment by koehntopp** [comment]
OK, turns out I was just stupid. I thought I had the duration in minutes and seconds and needed to convert ist, but it was in seconds all along 🤦🏻‍♂️

Now the question remains why it worked at all 🤣

Anyway, thank you!!

**Comment by tranxuanthang** [comment]
The API documentation page for LRCLIB is available here: 🎉

https://lrclib.net/docs
