### ISSUE TITLE
"Ran out of memory" error

### ISSUE THREAD

**Issue by heartbraden** [tranxuanthang/lrcget#19]
I just installed it, pointed it to my music directory (just over 1TB of music, around 110k songs) and got a loading icon for several minutes until it errored out and won't get past that error. I'm on Win10 and have 32GB of RAM but when I start LRCGET it uses more and more until it errors out.

**Comment by tranxuanthang** [comment]
The `fs_track::load_tracks_from_directories` function implementation is a bit naive, as it tries to load and process all files at once, while allocating a huge amount of data in memory.

I have just done some improvement about this in https://github.com/tranxuanthang/lrcget/commit/449f6b46b64b4639c7cb6b65785ba395a74cfc9b but more work need to be done for LRCGET to handle huge library smoothly.

**Comment by tranxuanthang** [comment]
Version 0.2.1 has some improvement about memory consumption when importing huge directories, and it also shows the progress while scanning for tracks:

https://github.com/tranxuanthang/lrcget/releases

**Comment by heartbraden** [comment]
Version 0.2.1 still gives me this error.  It successfully shows the progress while scanning for tracks and gets through all ~112k songs, but then my RAM just shoots through the roof and the application crashes and gives me the same error as before.

**Comment by byrongamatos** [comment]
I am facing the same issue, with a library of 50k songs. The initial directory scan completes succesfuly, and i can see all the songs in the list, but clicking download all or going to the artists tab, throws the out of memory error

**Comment by starkgate** [comment]
> I am facing the same issue, with a library of 50k songs. The initial directory scan completes succesfuly, and i can see all the songs in the list, but clicking download all or going to the artists tab, throws the out of memory error, windows 11 64GB of RAM

Same here with 60k songs

**Comment by lattedesu** [comment]
I'm having the same issue.

My Windows 11 is having 32 GBs of ram, and the app utilizes maximum of 9.5GBish for 40k songs, and after a while the app crashes saying out of memory.

**Comment by tranxuanthang** [comment]
@heartbraden @byrongamatos @starkgate @lattedesu @tangsgod @TacoCake The newest release v0.3.0 vastly improve performance specifically for this issue. Unfortunately I do not have that large music library as some of you here to test it properly, but there is good feedback from @eprudspk in #44 with 7k songs. Could you help me try this version?

https://github.com/tranxuanthang/lrcget/releases/tag/0.3.0

**Comment by Ardakilic** [comment]
Just started lrcget 0.3.0 on my big library, it's been 5 mins, can confirm and UI is responsive as butter and no CPU pikes at all. Thank you!

**Comment by tangsgod** [comment]
@tranxuanthang  i can't test for now because it is force closing when i start it

**Comment by starkgate** [comment]
Can also confirm it works beautifully with 60k songs loaded. Thanks for the update!

![grafik](https://github.com/tranxuanthang/lrcget/assets/12874678/12251d03-5268-4334-a426-b981cf37207b)

**Comment by TacoCake** [comment]
Can also confirm it fixes pretty much every performance issue I had, thanks !

**Comment by jeffreyswiggins** [comment]
So just found this app and have a library of just shy of 200,000 tracks that are mostly FLAc audio.  Using Ubuntu Desktop 22.04 and your AppImage release I pointed it to my top level and let it rip.  So far it has been "initializing library" for over 10 minutes but the CPU and memory is good, and I can tell from Glances Container that I have running that it is processing and not just hung up as it fluctuates.  I will just let it run over night and see what it does.  Interested to see the results as I have a ton of "Classical" and "Jazz" that I doubt will find much and really would have much as they are instrumental, also have lots and lots of music that should have lyric files.

Thanks for making this available!
