### ISSUE TITLE
Manual search

### ISSUE THREAD

**Issue by Dr-Blank** [tranxuanthang/lrcget#2]
There are some songs where I know the lyrics exists on musixmatch, it's just that the metadata might be a little off which fails the matching of song to your database.

If there was a way to modify the search query, e.g. artist or song name, such that I could try matching to your database and retrieve the lyrics. 

This is a wonderful piece of software, thank you for making this. It relieved me of so much pain of finding lyrics for every song individually and renaming the file to match the song (that is just brilliant)!!

**Comment by tranxuanthang** [comment]
I'm working on a official homepage for lrclib which including a search feature, but in the meantime you can use these APIs to find the lyrics you want:

- https://lrclib.net/api/search?q={query}
- https://lrclib.net/api/get/{id}

For example:

- https://lrclib.net/api/search?q=CHVRCHES
- https://lrclib.net/api/get/2392

**Comment by Dr-Blank** [comment]
This api is awesome. I wish there was a plugin for beets which used this api. It would be splendid.

**Comment by Dr-Blank** [comment]
> I added Lrclib to my beets lyrics plugin

Sounds amazing, I'll have to try once I get home!

**Comment by tranxuanthang** [comment]
Manual search feature is now available in v0.2.1:

https://github.com/tranxuanthang/lrcget/releases

You can also search for lyrics by visiting LRCLIB homepage:

https://lrclib.net
