### ISSUE TITLE
Sometimes capitalisation of albums / song names messes up the matched lyrics

### ISSUE THREAD

**Issue by Virtuo1** [tranxuanthang/lrcget#20]
See for example

Album name: Just As I Am
https://lrclib.net/api/get?artist_name=Bill%20Withers&track_name=Ain%27t%20No%20Sunshine&album_name=Just%20As%20I%20Am&duration=126

Album name: Just as I am
https://lrclib.net/api/get?artist_name=Bill%20Withers&track_name=Ain%27t%20No%20Sunshine&album_name=Just%20as%20I%20am&duration=126

One returns a result with only plain lyrics while the other has both plain and synced lyrics.

These are otherwise identical matches and I personally think it should prioritise matching the one with synced lyrics!

Maybe this is the wrong place to submit an issue since the problem is the api and not the application, but thought I should let you know..

**Comment by tranxuanthang** [comment]
The `/get` API is now case insensitive and won't create new track records anymore if only the letter cases are different. Both of your request is now point to the same track ID 946782.

Searching with `/search` API (for example, https://lrclib.net/search/ain't%20no%20sunshine%20bill%20withers%20just%20as%20i%20am) and you will still see a lot of duplicated (but with different letter cases) records, but I decided I will leave it there for now.
