### ISSUE TITLE
feature request: WAV audio support

### ISSUE THREAD

**Issue by raxdraws** [tranxuanthang/lrcget#21]
I wish the program can read .WAV audio files, because all my library are conformed with uncompressed audio files (bandcamp, spotify, youtube music, etc. audio files)

**Comment by tranxuanthang** [comment]
Resolved in v0.3.0. Could you verify it?

https://github.com/tranxuanthang/lrcget/releases/tag/0.3.0

**Comment by raxdraws** [comment]
yes, it works good, the lyrics are saved in the .wav files
