### ISSUE TITLE
macOS Version GUI Bugs

### ISSUE THREAD

**Issue by SawkeeReemo** [tranxuanthang/lrcget#25]
First of all, thank you! This is a great little app, impressive work so far!
I just wanted to drop by and give you a few notes on some macOS issues I've found that you hopefully find helpful as you work:

1. Can't scroll on any page. So I can never see anything past what gets loaded on the screen at the beginning.
2. No stop button for music player, have to quit the app.

Other than that, I think it works really well. Would love to know where you are pulling these from, and if it's possible to add more sources. Thanks!

**Comment by tranxuanthang** [comment]
I would gladly accept a PR from anyone who are interested in fixing this issue, because I do not own a mac device and neither do people around me.

**Comment by tueksta** [comment]
I'm on OSX Ventura 13.6.1 and can't confirm this. Scrolling works fine everywhere, except in the lyrics window where it's not supposed to work, as autoscrolling along with the music is enforced.

**Comment by tranxuanthang** [comment]
@SawkeeReemo @tueksta Could you verify all the issues on macOS after the latest update? The scroll bar is now webview native, so there should be no strange problems. Search result is now also scrollable properly.

https://github.com/tranxuanthang/lrcget/releases/tag/0.3.0

**Comment by tranxuanthang** [comment]
Closing this issue to clean up. If you are still facing any problems, feel free to reopen this or open a new one!
