### ISSUE TITLE
ALAC (m4a) File Playback Support

### ISSUE THREAD

**Issue by nattadasu** [tranxuanthang/lrcget#26]
As I used ALAC for my music collections to iTunes, please add support to play ALAC files. I'm quite unsure if the application can play AAC files, however, as I personally don't own it.

The app does detect the file and able to read the metadata, but it unable to play the music, making it harder to check if the lyric matches with the song, or doing lyric editing and correction.

**Comment by tranxuanthang** [comment]
What platform are you using (Windows, Linux,...)? I've just tested playing .m4a files from LRCGET on Linux and it plays just fine.

**Comment by nattadasu** [comment]
I'm using Windows.

FYI, all of ALAC files were transcoded from FLAC with fre:ac. I didn't modify any encoding setting, so that's shouldn't be problem tbh.

**Comment by tranxuanthang** [comment]
Weird, I tried playing my .m4a tracks yesterday on Windows but cannot reproduce. I will try using fre:ac later when I have some free time.

**Comment by nattadasu** [comment]
Alright, I've been experimenting with LRCGET and fre:ac, and it seems LRCGET unable to play ALAC file. AAC (loosy) under the same file format (`.m4a`) will run perfectly fine, but not loseless.

The file I'm converting is from 24-bit FLAC, and in fre:ac, I leave the settings as default:

![image](https://github.com/tranxuanthang/lrcget/assets/49780229/8517103c-b96a-4418-9744-7040c1f80e69)
![image](https://github.com/tranxuanthang/lrcget/assets/49780229/ad77766c-3d8b-41cf-999e-0316c194c9fa)

**Comment by tranxuanthang** [comment]
There is big change regarding audio playback support in v0.3.0, could you recheck if the issue still persist?

https://github.com/tranxuanthang/lrcget/releases/tag/0.3.0

**Comment by nattadasu** [comment]
The issue seems have been fixed. Thanks! :D
