### ISSUE TITLE
How to publish plain text lyrics?

### ISSUE THREAD

**Issue by shipurjan** [tranxuanthang/lrcget#34]
I would like to publish plain text lyrics, because I sometimes don't want to go through an entire album to sync lyrics, so it could better that at least plain text lyrics were available for other people to later easier sync them.

I can download plain text lyrics, but I can't publish it (or I don't see where).

**Comment by Dr-Blank** [comment]
you can do it directly through api if you know how. however, the lrcget client does not allow submitting plain lyrics as of writing

**Comment by shipurjan** [comment]
Is this by design? Maybe you could add a button for it

**Comment by Dr-Blank** [comment]
yes you could do it if you can create a PR

**Comment by tranxuanthang** [comment]
Resolved in v0.3.0, thank you again for your work!
