### ISSUE TITLE
Removing settings

### ISSUE THREAD

**Issue by strozek-xx** [tranxuanthang/lrcget#39]
I selected too many folders and now lrcget is stuck with the 'Loading library...' message. Left it on overnight, no change. 
Uninstalled and re-installed, and again the Loading library message. How can i reset or delete the settings? Devuan Daedalus.

**Comment by shipurjan** [comment]
If you're on Windows try deleting the files in the path: `%appdata%/net.lrclib.lrcget`

**Comment by strozek-xx** [comment]
Solved. I installed lrcget_0.2.1_amd64_ubuntu_22.04.deb. After uninstall the leftover files can be found with `locate`. 
So i can't recommend selecting an external drive with 2000+ folders.
