### ISSUE TITLE
It fails to retrieve some lyrics on the 1st run but succeeds in the 2nd

### ISSUE THREAD

**Issue by 5wHN28Dg** [tranxuanthang/lrcget#4]
I get an error message "Something bad happened when retrieving the lyrics" I'm paraphrasing a little bit

**Comment by tranxuanthang** [comment]
Maybe because of some proxy issues of my backend.

**Comment by Seb3thehacker** [comment]
I am also getting this issue for some songs, "Internal Server Error: Something bad happened when retrieving the lyrics." Other than this its running perfectly on linux!

**Comment by tranxuanthang** [comment]
Many things were changed in LRCLIB, and this issue might possibly be fixed a while ago. I will close this for now, but please feel free to reopen or create a new issue if there are any other problems.
