### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by SonOfTheKingdom** [tranxuanthang/lrcget#45]
App won't open on Windows 10. I try to open the app even with admin privileges and nothing happens.

**Comment by tranxuanthang** [comment]
If you are using Windows 10 LTSC, or have tried running some scripts to debloat Windows 10 (which will uninstall Microsoft Edge and its webview component), you may need to reinstall WebView2 Bootstrapper:

https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

Related: https://github.com/tranxuanthang/lrcget/issues/16

**Comment by SonOfTheKingdom** [comment]
When trying to install it, it says that Microsoft Edge WebView2 is already installed. I have indeed debloated my PC and doesn't have Microsoft Edge. Do I need to reinstall it then?

**Comment by tranxuanthang** [comment]
> Do I need to reinstall it then?

I don't really know what went wrong, but I think you should give it a try. For my Windows 10 LTSC install, I only need to install WebView2 and LRCGET works just fine.

**Comment by tranxuanthang** [comment]
I'm glad it worked!

**Comment by Maguz0** [comment]
instalen microsoft edge oficial de la web y soluciona rapido
