### ISSUE TITLE
feat: Shift (+/-) all the selected lines instead of the last one

### ISSUE THREAD

**Issue by Dr-Blank** [tranxuanthang/lrcget#55]
When selecting all lines in editing mode, cursor is on the last line selected. Hence pressing +/- shifts only the line with the cursor.

This feat would shift all the lines selected using +/- buttons.

**Comment by tranxuanthang** [comment]
Added in the following commit (hopefully): https://github.com/tranxuanthang/lrcget/commit/3f375a7aa908fd9fc501011c339d68f1585391c2

**Comment by tranxuanthang** [comment]
Added in [v0.5.0](https://github.com/tranxuanthang/lrcget/releases/tag/0.5.0) 🎉!
