### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by abhishekabhi789** [tranxuanthang/lrcget#63]
If possible, please add dark theme. Light theme causing eye fatigue when syncing lyrics.

**Comment by tranxuanthang** [comment]
This is possible to implement to LRCGET by using Tailwind CSS's `dark:` variant (https://tailwindcss.com/docs/dark-mode). If someone wants to implement this, then a PR is welcome!

**Comment by darkpixlz** [comment]
going to bump this for official support again. hurts my eyes so much to use with the bright white and off pink theme 😭

**Comment by corylowry12** [comment]
This is much needed :)

**Comment by tranxuanthang** [comment]
There is a WIP prototype of dark mode in #104.

**Comment by corylowry12** [comment]
#137

**Comment by tranxuanthang** [comment]
Available on [v0.9.0](https://github.com/tranxuanthang/lrcget/releases/tag/0.9.0)!
