### ISSUE TITLE
I can't add directories into the app

### ISSUE THREAD

**Issue by gejir** [tranxuanthang/lrcget#7]
I just installed V 0.11, but it doesn't seem to work for me
When I try to add directories, nothing happens. I can't even drag and drop folders/songs.
Also, for some reason, I can't close/maximize/minimize the app. I have to either ALT+F4 or use Task Manager
I only downloaded LRCGET_0.1.1_x64-setup.exe so I'm wondering if I was meant to install something else
Thanks for your time

**Comment by tranxuanthang** [comment]
There was a bug in 0.1.1. I'm building newer version right now.

Also, your chosen setup file is fine. The file that named *LRCGET_0.1.1_x64-setup.exe* won't ask for UAC permission and will only install in user directory. The *LRCGET_0.1.1_x64_en-US.msi* file difference is that it installs the app in *Program File* directory, requires UAC permission and will automatically install webview2, which is only needed for Windows 7 or Windows 10 LTSC users.

**Comment by gejir** [comment]
Oh okay. Thanks for letting me know

**Comment by tranxuanthang** [comment]
v0.1.2 is released, can you check it? https://github.com/tranxuanthang/lrcget/releases/tag/0.1.2

**Comment by gejir** [comment]
Yup, it's fixed. Thanks
Though, I have a question. What do I do in case of an LRC not being in the database?

**Comment by tranxuanthang** [comment]
Thank you for confirming!

> What do I do in case of an LRC not being in the database?

In the future, I'm planning to allow people to create, edit and synchronize LRC lyrics right in the app, and contribute it to LRCLIB service. But right now there isn't much for you to do other than get the lyrics from other sources.
