### ISSUE TITLE
unable to use the music player 

### ISSUE THREAD

**Issue by GitEin11** [tranxuanthang/lrcget#8]
currently using ubuntu 20.04: tried both deb and appimage
when play button is pressed nothing happens, i already have the mp3 and synched lrc on the same directory

**Comment by tranxuanthang** [comment]
Linux build is currently suffer from the bug https://github.com/tauri-apps/tauri/issues/3725

I came up with a nice workaround at the [linux-playback-fix](https://github.com/tranxuanthang/lrcget/tree/linux-playback-fix) branch. But it has a few security related problems, so I haven't merged it into the main branch yet.

**Comment by tranxuanthang** [comment]
I decided to just release it now and improve/refactor it later. Check out v0.1.4 here:

https://github.com/tranxuanthang/lrcget/releases/tag/0.1.4

**Comment by GitEin11** [comment]
> I decided to just release it now and improve/refactor it later. Check out v0.1.4 here:
> 
> https://github.com/tranxuanthang/lrcget/releases/tag/0.1.4

thnx
