### ISSUE TITLE
Instrumental music is wrongly identified has having lyrics (lyrics from another band and track)

### ISSUE THREAD

**Issue by MustThinkOfAName** [tranxuanthang/lrcget#80]
Hey there!

I first wanted to thank you for this wonderful tool and your work on it. Not only it works great but it also looks and feels amazing to use.

I noticed an issue on at least one track in my library. It's 0078H - Dead cities, Red Seas & Lost Ghosts - M83.

This song has no lyrics, LRCGET recognizes the song correctly (even in the lyrics search engine)  and yet lyrics of another song by another band are played (Don’t - The Big Room -  M2M).

What should be done in that scenario? Should there be a way to display the track as being instrumental even tho lyrics are somehow submitted?

Thank you again.

**Comment by tranxuanthang** [comment]
Hey, thank you for your good words, I'm glad you like it!

The general approach when you see a song having wrong lyrics is that you republish the right version of it. That way you and other people will no longer seeing the wrong lyrics in the future.

You can publish a new lyrics in Lyrics Editor window. For any song that should be instrumental, you simply need to publish empty lyrics content, and LRCLIB will automatically mark that song as instrumental.
