### ISSUE TITLE
"Download All Lyrics" doesn't work for tracks, only for albums

### ISSUE THREAD

**Issue by tangsgod** [tranxuanthang/lrcget#81]
You can see in this video that the "Download All Lyrics" doesn't work when on Tracks section, but does in Albums section.

The folder here is about 120 000 tracks

[https://youtu.be/FGNivVkh7ZY?si=Y4cJQSC5IsGBNLdt](https://youtu.be/FGNivVkh7ZY?si=Y4cJQSC5IsGBNLdt)

**Comment by tranxuanthang** [comment]
@tangsgod I'm looking into it, but it doesn't seem to be related to a performance issue.

Could you help me check the console log to see if there is anything wrong?

1. Click the spider button
2. In the developer tool, choose tab Console
3. Try clicking "Download all lyrics" button
4. See if there is anything strange or error log shown in console
5. Send me the screenshot or text of the error if any

![image](https://github.com/tranxuanthang/lrcget/assets/15942946/98db39a5-1a54-4147-ac42-5ff3005921a2)

**Comment by tangsgod** [comment]
Thank you for your help

Here is the screenshot of the console after hitting the Download button for
90 000 songs

Le mer. 22 mai 2024 à 17:51, tranxuanthang ***@***.***> a
écrit :

**Comment by tranxuanthang** [comment]
@tangsgod I'm not seeing any image uploaded, could you reupload it?

**Comment by tangsgod** [comment]
Of course, here it is

Le ven. 24 mai 2024 à 11:13, tranxuanthang ***@***.***> a
écrit :

**Comment by tangsgod** [comment]
The image is in the mail

**Comment by tranxuanthang** [comment]
@tangsgod Maybe GitHub doesn't reupload your attachment to GitHub issue, and I also cannot see it in my inbox. If you prefer emails, could you send it directly to my email address?

My email: hoangtudevops@protonmail.com

**Comment by tranxuanthang** [comment]
It is probably resolved in commit https://github.com/tranxuanthang/lrcget/commit/0ec12966a521a40801a795c70e241be514b4dd22, released in v0.3.2. If you have any problems, feel free to leave a comment and I will reopen this, thank you!
