### ISSUE TITLE
Playback Hotkey is still being executed while looking up lyric

### ISSUE THREAD

**Issue by nattadasu** [tranxuanthang/lrcget#82]
It seems that hotkey event listener (implemented in fcfd2eae1daf5849e29d73f8d1be30526885c544) does not get disable in lyric lookup/search modal/popup.

Additionally, I found weird bug before I want to submit the issue related to this; the listener wasn't doing properly, it affected while editing the lyric too. But managed to "fix" it by simply restarting the app.

### Steps to Reproduce

0. Update local music database
1. Select random file, either unsync, sync, or none
2. Open search modal
3. Keysmash <kbd>Space</kbd> in text fields

### Expected result

User is able to input whitespace without making the app plays/pauses the file

### Actual result

* When debugger > console enabled, app does not log "enabled hotkey!" or "disabled hotkey!" during the modal opened.
* However, if debugger window opened before, opening the modal returns "is hotkey: true" instead

### System Info

* App version: 0.3.1
* Windows: 11, 23H2

**Comment by tranxuanthang** [comment]
I see, I remember I did fix it for lyrics editor modal, but I forgot the lyrics search one.

I will make a hotfix release, but I wonder if there is a global way to do this. For example, it should automatically disable hotkey detection when focusing on any kind of textbox.

**Comment by tranxuanthang** [comment]
I released the fix in 0.3.2 version. Could you help me verify it?

**Comment by nattadasu** [comment]
Aight, I've upgraded to https://github.com/tranxuanthang/lrcget/releases/tag/0.3.2 and it works great now.

Thanks for the hotfix! 😄
