### ISSUE TITLE
Songs not showing up

### ISSUE THREAD

**Issue by bkev** [tranxuanthang/lrcget#90]
I'd like to use this tool but it seems like my mp3s have too many tags? I use MusicBrainz Picard to add extra tags and I think they are confusing things and the songs aren't showing. 

Is it possible to get lrcget to only use the artist and album tag or somehow ignore any other tags?

Thanks.

**Comment by tranxuanthang** [comment]
I'm closing this to clean up the issues list. If you are still facing this issue, please discuss about it in #92.
