### ISSUE TITLE
Add Syrics as source?

### ISSUE THREAD

**Issue by nothing2obvi** [tranxuanthang/lrcget#93]
Hello. Is there a simple way to use [Syrics](https://github.com/akashrchandran/spotify-lyrics-api) as a source?

I like Syrics' [web version](https://syrics-web-akashrchandran.vercel.app) but if I could combine Syrics and LRCGET that would be amazing. Unless they use the same source?? I felt like I didn't get lyrics for many of my songs via LRCGET.

**Comment by tranxuanthang** [comment]
> I like Syrics' [web version](https://syrics-web-akashrchandran.vercel.app/) but if I could combine Syrics and LRCGET that would be amazing. Unless they use the same source?? I felt like I didn't get lyrics for many of my songs via LRCGET.

I'm quite certain that lrclib.net (which LRCGET uses under the hood) should cover most, if not all, of the lyrics that Syrics has ;-)
