### ISSUE TITLE
Removing folder removes all folders below it

### ISSUE THREAD

**Issue by grrrrr** [tranxuanthang/lrcget#98]
The logic in how folders are removed from the `scanning directories` section might be a bit off.   

### Issue

 If you remove the top most folder in a list it removes everything below it but if you remove the bottom most folder it only removes that one folder

eg.

```
folder_1 X
folder_2 X
folder_3 X
folder_4 X
```

Select the X by folder 1 and folder 2, 3 and 4 also get removed

Select the X by folder 3 and folder 3 and 4 get removed

Select the X by folder 4 and only folder 4 gets removed.

### Expected results

Clicking the X to remove a folder only removes that particular folder from the list

**Comment by tranxuanthang** [comment]
This should be fixed in commit https://github.com/tranxuanthang/lrcget/commit/284e710ed9f5b5cf1a90d48599e24a4b593a7a87, I will make a new release soon!

**Comment by tranxuanthang** [comment]
Fixed in v0.5.0 🎉
